### ISSUE TITLE
Attempting to change language causes crash

### ISSUE THREAD

**Issue by jcperil** [zhanghai/MaterialFiles#1009]
Device: Redmi Note 10 Pro
Android: 13
Material Files: v1.6.0 (F-Droid)

Steps to reproduce:
1. Open navigation drawer
2. Go to Settings
3. Tap on Language
4. The app either returns home or causes a crash.

The log generated by the system is attached below:

<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:75)
	at android.app.Activity.performCreate(Activity.java:8523)
	at android.app.Activity.performCreate(Activity.java:8487)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	... 12 more

```
</details>
<hr>

**Comment by zhanghai** [comment]
What is your system version? And is it official ROM?

The log shows that there is clearly a  bug in your system Settings app... So you'll need to report this to your system vendor.

**Comment by jcperil** [comment]
It is official MIUI 14.

> So you'll need to report this to your system vendor.

Done.
