### ISSUE TITLE
Sui not working with R8 full mode

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#1034]
Something needs to be kept in `Shizuku-API`?

This is a continuation of #1026.

**Comment by zhanghai** [comment]
@Citrinae-Lime @RikkaW FYI

**Comment by zhanghai** [comment]
From provided logs:

```
[10-01 10:58:07.547 13188:13188 W/SuiUserServiceStarter]
unable to start service me.zhanghai.android.files/me.zhanghai.android.files.provider.root.x...
java.lang.InstantiationException: java.lang.Class<me.zhanghai.android.files.provider.root.x> cannot be instantiated
 at java.lang.Class.newInstance(Native Method)
 at rikka.sui.q1.a(SourceFile:188)
 at rikka.sui.server.userservice.Starter.main(SourceFile:14)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
```
