### ISSUE TITLE
Crash after system update to Android 14

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#1038]
```
Fatal Exception: java.lang.IllegalArgumentException: Invalid URI: content
       at android.provider.DocumentsContract.getTreeDocumentId(DocumentsContract.java:1289)
       at me.zhanghai.android.files.file.DocumentTreeUri.getDocumentId-impl(DocumentTreeUri.java:6)
       at me.zhanghai.android.files.file.DocumentTreeUriKt.getDisplayName-fg4uSDU(DocumentTreeUri.kt:6)
       at me.zhanghai.android.files.storage.DocumentTree.getDefaultName(DocumentTree.java:1)
       at me.zhanghai.android.files.storage.Storage.getName(Storage.java:1)
       at me.zhanghai.android.files.navigation.PathStorageItem.getTitle(PathStorageItem.java:1)
       at me.zhanghai.android.files.navigation.NavigationListAdapter.onBindViewHolder(NavigationListAdapter.java:122)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:147)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:1248)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1248)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:54)
       at androidx.recyclerview.widget.LinearLayoutManager.findLastCompletelyVisibleItemPosition(LinearLayoutManager.java:1)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:847)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:123)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:145)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3583)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
       at android.view.Choreographer.doCallbacks(Choreographer.java:952)
       at android.view.Choreographer.doFrame(Choreographer.java:882)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

<details><summary>Obfuscated stacktrace</summary>

```
Fatal Exception: java.lang.IllegalArgumentException: Invalid URI: content
       at android.provider.DocumentsContract.getTreeDocumentId(DocumentsContract.java:1289)
       at me.zhanghai.android.files.file.DocumentTreeUri.getDocumentId-impl(DocumentTreeUri.java:6)
       at me.zhanghai.android.files.file.DocumentTreeUriKt.getDisplayName-fg4uSDU(DocumentTreeUri.kt:6)
       at me.zhanghai.android.files.storage.DocumentTree.getDefaultName(DocumentTree.java:1)
       at me.zhanghai.android.files.storage.Storage.getName(Storage.java:1)
       at me.zhanghai.android.files.navigation.PathStorageItem.getTitle(PathStorageItem.java:1)
       at me.zhanghai.android.files.navigation.NavigationListAdapter.onBindViewHolder(NavigationListAdapter.java:122)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:147)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:1248)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1248)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:54)
       at androidx.recyclerview.widget.LinearLayoutManager.b1(LinearLayoutManager.java:1)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:847)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:123)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:145)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6440)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3583)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
       at android.view.Choreographer.doCallbacks(Choreographer.java:952)
       at android.view.Choreographer.doFrame(Choreographer.java:882)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
</summary>

**Comment by zhanghai** [comment]
Root cause
