### ISSUE TITLE
Crash when trying to allow Manage All Files permission on CCwGTV

### ISSUE THREAD

**Issue by andybotting** [zhanghai/MaterialFiles#1146]
Just trying to set up a Chromecast with Google TV running Android 12.

Apologies if this has been filed before - I couldn't see anything when I was looking.

After I click 'OK' for the 'App needs access...' dialog, the app immediately dies.

```
I ActivityTaskManager: START u0 {act=android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION dat=package:me.zhanghai.android.files} from uid 10103
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: me.zhanghai.android.files, PID: 9931
E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION dat=package:me.zhanghai.android.files }
E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5404)
E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
E AndroidRuntime: 	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:854)
E AndroidRuntime: 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:245)
E AndroidRuntime: 	at androidx.activity.ComponentActivity$1.onLaunch(ComponentActivity.java:239)
E AndroidRuntime: 	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:173)
E AndroidRuntime: 	at androidx.fragment.app.Fragment$10.launch(Fragment.java:3632)
E AndroidRuntime: 	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
E AndroidRuntime: 	at me.zhanghai.android.files.filelist.FileListFragment.requestAllFilesAccess(FileListFragment.kt:1386)
E AndroidRuntime: 	at me.zhanghai.android.files.filelist.FileListFragment.onShowRequestAllFilesAccessRationaleResult(FileListFragment.kt:1376)
E AndroidRuntime: 	at me.zhanghai.android.files.filelist.ShowRequestAllFilesAccessRationaleDialogFragment.onCreateDialog$lambda$0(ShowRequestAllFilesAccessRationaleDialogFragment.kt:25)
E AndroidRuntime: 	at me.zhanghai.android.files.filelist.ShowRequestAllFilesAccessRationaleDialogFragment.$r8$lambda$s2EbU9CPXur1lWZK39ErbWdQnP4(Unknown Source:0)
E AndroidRuntime: 	at me.zhanghai.android.files.filelist.ShowRequestAllFilesAccessRationaleDialogFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

When I go into the Android App info and look under it's permissions, there's nothing to select.

In contrast, I did manage to get what I needed from AnExplorer. When I opened it, I got presented with an 'Accept' button, but later I had to enable the extra 'Allow any time' for it to actually work properly.

I also tried 'Amaze' and it failed in the same way as this app.

I think Android TV (especially from v11) things get complicated around files, but I don't remember seeing an issue like this before.

**Comment by andybotting** [comment]
Ah sorry, found a duplicate in issue 875
