### ISSUE TITLE
Error activating root mode on Lollipop device

### ISSUE THREAD

**Issue by AnotherJavaUser** [zhanghai/MaterialFiles#1161]
I installed the application on a Samsung J1 Ace (SM-J111M, j1acevelte) that is rooted with SuperSU. When activating root mode in the explorer and reloading, I get the following error:

![Screenshot_2024-03-17-11-46-01](https://github.com/zhanghai/MaterialFiles/assets/140354076/2c41ea47-1016-4467-a490-1d259297b965)

I obviously granted root permissions in SuperSU. And in normal mode it works fine. The exact version is Android 5.1.1.
I know it's pretty old, but you might want to correct it.

**Comment by zhanghai** [comment]
Any stacktrace in logcat? The error means that the root process was launched but crashed.

**Comment by zhanghai** [comment]
From `logcat.txt`:

```
W/IPC     ( 4892): Failed to create package context as user: 0
W/IPC     ( 4892): java.lang.NoSuchMethodException: of [int]
W/IPC     ( 4892): 	at java.lang.Class.getDeclaredMethod(Class.java:638)
W/IPC     ( 4892): 	at com.topjohnwu.superuser.internal.RootServerMain.<init>(SourceFile:0)
W/IPC     ( 4892): 	at com.topjohnwu.superuser.internal.RootServerMain.main(SourceFile)
W/IPC     ( 4892): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
W/IPC     ( 4892): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:255)
```

It's a `libsu` compatiblity issue so I've opened https://github.com/topjohnwu/libsu/issues/180 for you and please track it there.
