### ISSUE TITLE
FTP tile causes crash

### ISSUE THREAD

**Issue by lucaxvi** [zhanghai/MaterialFiles#1238]
Tapping the FTP server quick setting tile in the notification panel crashes the app (version 1.7.2, Android 14).

F-Droid and Google Play Store versions are both affected.

```
05-25 18:39:40.286  2390  5188 W ActivityManager: startForegroundService() not allowed due to mAllowStartForeground false: service me.zhanghai.android.files/.ftpserver.FtpServerService
05-25 18:39:40.288 28802 28802 D AndroidRuntime: Shutting down VM
05-25 18:39:40.290 28802 28802 E AndroidRuntime: FATAL EXCEPTION: main
05-25 18:39:40.290 28802 28802 E AndroidRuntime: Process: me.zhanghai.android.files, PID: 28802
05-25 18:39:40.290 28802 28802 E AndroidRuntime: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service me.zhanghai.android.files/.ftpserver.FtpServerService
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Parcel.readParcelable(Parcel.java:4852)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3041)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3024)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2966)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6013)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1931)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1906)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at D.c.b(SourceFile:1)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at G4.i.f(SourceFile:51)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at me.zhanghai.android.files.ftpserver.FtpServerTileService.onClick(SourceFile:23)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:494)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-25 18:39:40.290 28802 28802 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
05-25 18:39:40.294  2390 28827 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-25 18:39:40.297  2390  2437 I ActivityManager: Showing crash dialog for package me.zhanghai.android.files u0
```

**Comment by zhanghai** [comment]
Is this occasional or always happening? I think there's a bug in AOSP for sometimes disallowing apps to start foreground service from notification tiles.

**Comment by lucaxvi** [comment]
It happens every time. I don't recall it happening in Android 13. Could [this](https://developer.android.com/about/versions/14/changes/fgs-types-required#include-fgs-type-runtime) be relevant?

**Comment by zhanghai** [comment]
> If the foreground service type is not specified in the call, the type defaults to the values defined in the manifest. If you didn't specify the service type in the manifest, the system throws MissingForegroundServiceTypeException.

Since the exception is not `MissingForegroundServiceTypeException`, I don't think it's related.

However, this does seem reproducible so I'll look into it...

**Comment by bosko101** [comment]
Hi, is there any workaround about this bug? I have it too.

**Comment by zhanghai** [comment]
Note that this is an Android 14 bug https://issuetracker.google.com/issues/299506164 .

**Comment by leuasseurfarrelds247-arch** [comment]
[]()c9fd16ec2c204e78cab7bf1b602208cfae6d97e9
