### ISSUE TITLE
ava8.nio.file.FileSystemException: Unable to parse TLS packet header

### ISSUE THREAD

**Issue by R3tr0BoiDX** [zhanghai/MaterialFiles#1336]
Hey, I've tried to connect to my FTPS server via password authentication. I use self-signed certificates with self-hosted `vsftpd` instance in Docker. I connected my phone to ` logcat` to see what I get and pasted the stack trace below. Hit me up if you need to know anymore.

```
11-06 01:48:30.891  4365  4365 W System.err: java8.nio.file.FileSystemException: /: Unable to parse TLS packet header
11-06 01:48:30.891  4365  4365 W System.err: 	at I2.m0.K0(SourceFile:74)
11-06 01:48:30.891  4365  4365 W System.err: 	at L6.b.s(SourceFile:40)
11-06 01:48:30.891  4365  4365 W System.err: 	at B1.b.u0(SourceFile:12)
11-06 01:48:30.891  4365  4365 W System.err: 	at H2.p.call(SourceFile:313)
11-06 01:48:30.891  4365  4365 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
11-06 01:48:30.891  4365  4365 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-06 01:48:30.891  4365  4365 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-06 01:48:30.891  4365  4365 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
11-06 01:48:30.892  4365  4365 W System.err: Caused by: javax.net.ssl.SSLException: Unable to parse TLS packet header
11-06 01:48:30.892  4365  4365 W System.err: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:804)
11-06 01:48:30.892  4365  4365 W System.err: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:744)
11-06 01:48:30.892  4365  4365 W System.err: 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:709)
11-06 01:48:30.892  4365  4365 W System.err: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:898)
11-06 01:48:30.892  4365  4365 W System.err: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
11-06 01:48:30.892  4365  4365 W System.err: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
11-06 01:48:30.892  4365  4365 W System.err: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
11-06 01:48:30.892  4365  4365 W System.err: 	at h8.j.t(SourceFile:52)
11-06 01:48:30.892  4365  4365 W System.err: 	at h8.j.i(SourceFile:11)
11-06 01:48:30.892  4365  4365 W System.err: 	at M6.e.b(SourceFile:156)
11-06 01:48:30.892  4365  4365 W System.err: 	at M6.e.a(SourceFile:41)
11-06 01:48:30.892  4365  4365 W System.err: 	at M6.e.e(SourceFile:13)
11-06 01:48:30.892  4365  4365 W System.err: 	at L6.b.s(SourceFile:23)
11-06 01:48:30.892  4365  4365 W System.err: 	... 6 more
```

**Comment by R3tr0BoiDX** [comment]
Ohh, btw, I might mention. When I get shown where what is to fixed/implemented, I might be able to help with that :)
