### ISSUE TITLE
新手如何本地编译这个项目？

### ISSUE THREAD

**Issue by yangislet** [zhanghai/MaterialFiles#1349]
下载了这个项目，android studio 使用2024最新版本的，已经配置了NDK和cmake，但是项目找不到如何本地编译的教程，正常应该考虑一下菜鸟的（奢求一下）。另外cmake文件中说cmake最小的版本是3.6，但是cmake官方最新的版本才是3.3. 如果提供帮助，不胜感谢！

执行./gradlew build 提示如下错误：
```FAILURE: Build failed with an exception.

* What went wrong:
:app debug:x86 failed to configure C/C++
A problem occurred starting process 'command '/usr/bin/cmake''
org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/bin/cmake''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:396)
	at org.gradle.process.internal.ExecHandleRunner.lambda$run$3(ExecHandleRunner.java:102)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:101)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/usr/bin/cmake'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.int```

**Comment by zhanghai** [comment]
> cmake官方最新的版本才是3.3

CMake 官方最新版本是 3.31 https://cmake.org/download/
Android SDK Manager 里能下载到的也远比 3.3 更新。

一般的开发问题请自己去开发者社区求助。
