### ISSUE TITLE
ImageViewerActivity crashes when too many sibling URIs

### ISSUE THREAD

**Issue by vvb2060** [zhanghai/MaterialFiles#242]
```
02-23 12:36:02.797 10905 10905 E AndroidRuntime: FATAL EXCEPTION: main
02-23 12:36:02.797 10905 10905 E AndroidRuntime: Process: me.zhanghai.android.files, PID: 10905
02-23 12:36:02.797 10905 10905 E AndroidRuntime: java.lang.RuntimeException: Failure from system
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1730)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5263)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at a.k.a.d.startActivityForResult(Unknown Source:10)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at a.g.d.a.a(Unknown Source:2)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at a.k.a.d.a(Unknown Source:7)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at androidx.fragment.app.Fragment.a(:10)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at androidx.fragment.app.Fragment.a(Unknown Source:1)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at i.a.a.c.r.d.a(Unknown Source:0)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at me.zhanghai.android.files.filelist.FileListFragment.b(:14)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at me.zhanghai.android.files.filelist.FileListFragment.k(:16)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at me.zhanghai.android.files.filelist.FileListAdapter.a(Unknown Source:10)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at i.a.a.c.h.v.onClick(Unknown Source:4)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at android.view.View.performClick(View.java:7281)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7258)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at android.view.View.access$3700(View.java:804)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27995)
02-23 12:36:02.797 10905 10905 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:

```
google/walleye/walleye:R/RPP1.200123.016/6203814:user/release-keys
应用版本 1.0.2
在一个拥有大量文件的文件夹下打开任意文件时崩溃

**Comment by zhanghai** [comment]
1.0.1 有这个问题吗？

**Comment by zhanghai** [comment]
如果 1.0.1 里有这个问题，并且打开的文件是图像类型，原因大概是为了图像查看器能够左右滑动查看同目录下的文件往 `Intent` 里塞各个文件 `Uri` 的 `extra` 时塞太多了导致了 `TransactionTooLargeException` :/ 这个不是很好修，我只能想到给加到 `extra` 里的 `Uri` 数量加个魔法上限 :/

**Comment by vvb2060** [comment]
图片文件夹。旧版本点按文件无反应，理应出现使用某某应用打开的提示
