### ISSUE TITLE
一些建议(2)

### ISSUE THREAD

**Issue by naloder** [zhanghai/MaterialFiles#249]
- [ ] 文本编辑器中的多编码切换似乎还未支持
- [ ] 压缩格式库是否找到合适的解决方案了
- [ ] QQ的存储路径已变更，望更改
- [ ] 是否在后续版本中添加云盘存储读取支持
- [x] 对一些特殊后缀的文件的打开方式中无法显示文本编辑(似乎是系统bug，已修复)

**Comment by zhanghai** [comment]
For the fifth item, you can choose "Open with" and then "Open as".

**Comment by naloder** [comment]
@zhanghai 似乎出现了闪退，选择打开方式，打开为之后

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.android.internal.app.ChooserActivity$ChooserListAdapter.targetInfoForPosition(ChooserActivity.java:1108)
	at com.android.internal.app.ResolverActivity.startSelected(ResolverActivity.java:799)
	at com.android.internal.app.ChooserActivity.startSelected(ChooserActivity.java:434)
	at com.android.internal.app.ResolverActivity$5.onClick(ResolverActivity.java:1162)
	at com.miui.internal.app.AlertControllerImpl$ButtonHandler.handleMessage(AlertControllerImpl.java:225)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7542)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by naloder** [comment]
@zhanghai 小米8青春版，安卓10

**Comment by zhanghai** [comment]
I believe this is a MIUI bug as the intent chooser activity worked fine on my OnePlus and Pixel devices. The crash is in system so you might need to wait for a MIUI fix.

**Comment by naloder** [comment]
> I believe this is a MIUI bug as the intent chooser activity worked fine on my OnePlus and Pixel devices. The crash is in system so you might need to wait for a MIUI fix.

已编辑Issue，最后一项已解决，前面几个是否有后续进度(?)
