### ISSUE TITLE
SMB is crashed by com.hierynomus:smbj:0.11.1

### ISSUE THREAD

**Issue by sunjw** [zhanghai/MaterialFiles#542]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.zhanghai.android.files, PID: 23012
    java.lang.NoSuchMethodError: No virtual method getConfig()Lcom/hierynomus/smbj/SmbConfig; in class Lcom/hierynomus/smbj/connection/Connection; or its super classes (declaration of 'com.hierynomus.smbj.connection.Connection' appears in /data/app/~~Gc8YXAoXJp-EiaMfHd30CQ==/me.zhanghai.android.files-XS2pp0TlIhYprdFWQ1d68g==/base.apk!classes18.dex)
        at com.rapid7.helper.smbj.io.SMB2SessionMessage.<init>(SMB2SessionMessage.java:45)
        at com.rapid7.helper.smbj.share.NamedPipe.<init>(NamedPipe.java:51)
        at com.rapid7.client.dcerpc.transport.SMBTransportFactories.openPipe(SMBTransportFactories.java:99)
        at com.rapid7.client.dcerpc.transport.SMBTransportFactories.openAndHandleStatusPipeNotAvailable(SMBTransportFactories.java:74)
        at com.rapid7.client.dcerpc.transport.SMBTransportFactories.getTransport(SMBTransportFactories.java:58)
        at me.zhanghai.android.files.provider.smb.client.Client.openDirectoryIterator(Client.kt:91)
        at me.zhanghai.android.files.provider.smb.SmbFileSystemProvider.newDirectoryStream(SmbFileSystemProvider.kt:153)
        at java8.nio.file.Files.newDirectoryStream(Files.java:457)
        at me.zhanghai.android.files.provider.common.PathExtensionsKt.newDirectoryStream(PathExtensions.kt:144)
        at me.zhanghai.android.files.storage.EditSmbServerViewModel$connect$1$1.invoke(EditSmbServerViewModel.kt:34)
        at me.zhanghai.android.files.storage.EditSmbServerViewModel$connect$1$1.invoke(EditSmbServerViewModel.kt:29)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

The upstream issue here: https://github.com/hierynomus/smbj/issues/601

**Comment by zhanghai** [comment]
There seems to be other potential issues with SMBJ 0.11.1, so I'll just revert the update for safety.

https://github.com/hierynomus/smbj/issues/654

**Comment by zhanghai** [comment]
Could you help verify if SMB is working properly again after 5ec1a3f?

**Comment by sunjw** [comment]
SMB works again!

**Comment by zhanghai** [comment]
Thanks for checking!

**Comment by zhanghai** [comment]
I've retried the smbj upgrade with 7503833 since smbj-rpc 0.12.0 has been release to support smbj 0.11.x. So could you help verify again if SMB is still working properly after 7503833?

**Comment by sunjw** [comment]
7503833 seems work well.
