### ISSUE TITLE
[Bug Report] Crashes on app Split view

### ISSUE THREAD

**Issue by shuvashish76** [zhanghai/MaterialFiles#574]
Steps to Reproduce
1. Select any folder/file
2.  Click on the side 3 dont icon
3.  Click & hold Recent button for _split view_
4. Come back to Normal view
5. Choose any function besides **Cut** or **Copy**
App crashes
![Screenshot_2021-08-27-10-25-36](https://user-images.githubusercontent.com/48226312/131074730-e90c7f4d-0d5e-40ef-b9c8-1ce306571f45.jpeg)

https://user-images.githubusercontent.com/48226312/131075480-b1af23df-43be-4e9e-8590-8f691e633d3d.mp4

---

```
FATAL EXCEPTION: main
Process: me.zhanghai.android.files, PID: 25996
java.lang.IllegalStateException: Fragment FileListFragment{e0e7546} (d6d746dc-4244-4e0b-bfeb-03107e120b35) not attached to Activity
	at androidx.fragment.app.Fragment.u1(:3)
	at eb.j.z(:1)
	at me.zhanghai.android.files.filelist.FileListFragment.C1(:11)
	at me.zhanghai.android.files.filelist.FileListFragment.I(Unknown Source:1)
	at androidx.appcompat.widget.s0.a(:3)
	at androidx.appcompat.view.menu.e.e(Unknown Source:4)
	at androidx.appcompat.view.menu.e.r(:1)
	at l.d.onItemClick(:4)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3150)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4117)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3862)
	at androidx.appcompat.widget.j0.onTouchEvent(:2)
	at android.view.View.dispatchTouchEvent(View.java:11777)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2406)
	at android.view.View.dispatchPointerEvent(View.java:12016)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4809)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4623)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4180)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4307)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4188)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4364)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4180)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4188)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6682)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6656)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6617)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6785)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by shuvashish76** [comment]
https://github.com/TeamAmaze/AmazeFileManager/issues/2752#issuecomment-908941914
