### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by shuvashish76** [zhanghai/MaterialFiles#590]
**Steps to produce:**
1. Open device settings
2.  Storage> Internal storage> Photos & videos> Images
3.  Choose MaterialFiles (Open with Image viewer)

**Crash logs:**
```
FATAL EXCEPTION: main
Process: me.zhanghai.android.files, PID: 11630
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.zhanghai.android.files/me.zhanghai.android.files.viewer.image.ImageViewerActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at me.zhanghai.android.files.viewer.image.ImageViewerFragment.b(Unknown Source:17)
	at me.zhanghai.android.files.viewer.image.ImageViewerFragment.w1(Unknown Source:0)
	at me.zhanghai.android.files.viewer.image.ImageViewerFragment.W0(:2)
	at androidx.fragment.app.s.a(:5)
	at androidx.fragment.app.s.k(:8)
	at androidx.fragment.app.q.E(:8)
	at androidx.fragment.app.q.Z(Unknown Source:84)
	at androidx.fragment.app.q.C(:4)
	at androidx.fragment.app.q.w(:3)
	at w0.g.onStart(:4)
	at f.h.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7043)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
	... 9 more
```
**Device details:**
App version: 1.3.1 (25) [F-Droid]
Android version: 8.1.0
Model: Lenovo Tab4 8 plus (TB-8704X)

**Additional context:**
please check what type of crash it is & change title of this issue accordingly...

Thankyou🙏🏿

**Comment by zhanghai** [comment]
Thanks for reporting this issue! I can reproduce this and will find some time to take a look later...
