### ISSUE TITLE
kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by Kita2345** [zhanghai/MaterialFiles#615]
kotlin.UninitializedPropertyAccessException: lateinit property argsFile has not been initialized
	at me.zhanghai.android.files.viewer.text.b.c(:3)
	at me.zhanghai.android.files.viewer.text.a.a()
	at z0.z.getValue(:4)
	at me.zhanghai.android.files.viewer.text.TextEditorFragment.v1()
	at me.zhanghai.android.files.viewer.text.TextEditorFragment$b$a.y(:1)
	at cb.a.k(:2)
	at wb.f.a(:2)
	at ub.d.G(:1)
	at rb.a.k0(:6)
	at e.j.k(:2)
	at me.zhanghai.android.files.viewer.text.TextEditorFragment$b.y()
	at cb.a.k(:2)
	at rb.j0.run()
	at z0.f.b()
	at androidx.lifecycle.LifecycleController$observer$1.e(:9)
	at androidx.lifecycle.e$a.a()
	at androidx.lifecycle.e.j(:27)
	at androidx.lifecycle.e.h()
	at androidx.lifecycle.e.f()
	at androidx.fragment.app.s.p(:1)
	at androidx.fragment.app.s.k(:2)
	at androidx.fragment.app.q.S(:1)
	at androidx.fragment.app.q.w(:3)
	at w0.h.onStart(:11)
	at f.h.onStart()
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:5991)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5264)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

**Comment by zhanghai** [comment]
How can I reproduce this? Or it's just an one-off issue?

**Comment by Kita2345** [comment]
it's just an one-off issue
