### ISSUE TITLE
Crash when targetSdkVersion 30 

### ISSUE THREAD

**Issue by YangKee** [zhanghai/MaterialFiles#621]
when targetSdkVersion 30 
Device Android  API >=11   Crash 
Device Android  API <=10   OK

when targetSdkVersion 29
Device Android  API >=11   OK
Device Android  API <=10   OK

Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.zhanghai.android.files.compat.RestrictedHiddenApiAccess.allow(RestrictedHiddenApiAccess.kt:42)
        at me.zhanghai.android.files.app.AppInitializersKt.allowRestrictedHiddenApiAccess(AppInitializers.kt:40)
        at me.zhanghai.android.files.app.AppInitializersKt.access$allowRestrictedHiddenApiAccess(AppInitializers.kt:1)
        at me.zhanghai.android.files.app.AppInitializersKt$appInitializers$2.invoke(AppInitializers.kt:29)
        at me.zhanghai.android.files.app.AppInitializersKt$appInitializers$2.invoke(AppInitializers.kt:29)
        at me.zhanghai.android.files.app.AppProvider.onCreate(AppProvider.kt:19)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2394)

**Comment by zhanghai** [comment]
This app currently targets 29.
