### ISSUE TITLE
Crashes when editing a file in SFTP

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#654]
```
FATAL EXCEPTION: main
Process: me.zhanghai.android.files, PID: 23708
java.lang.NullPointerException: uri.host must not be null
	at va.c.l(Unknown Source:11)
	at e.d.i(:4)
	at d9.a.p(Unknown Source:28)
	at me.zhanghai.android.files.viewer.text.TextEditorFragment.V0(:3)
	at androidx.fragment.app.s.f(:7)
	at androidx.fragment.app.s.k(:8)
	at androidx.fragment.app.q.E(:8)
	at androidx.fragment.app.q.Z(Unknown Source:84)
	at androidx.fragment.app.q.C(:4)
	at androidx.fragment.app.q.w(:3)
	at w0.g.onStart(:4)
	at f.h.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by linsui** [comment]
Sorry, I can't reproduce it now. I did reproduce it twice.

**Comment by zhanghai** [comment]
It's a weird issue (uri.host == null) and I don't have a good idea how that happened (unless there are reproduction steps) :/
