### ISSUE TITLE
Crash when sharing a file from SFTP

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#656]
The app crashes when I tried to share a file in SFTP. I can't get the crash log but if I restart the app and enter the SFTP server it will crash again and I got

```
FATAL EXCEPTION: AsyncTask #7
Process: me.zhanghai.android.files, PID: 21648
java.lang.ArrayIndexOutOfBoundsException: src.length=1 srcPos=0 dst.length=256 dstPos=-4 length=1
	at java.lang.System.arraycopy(System.java:524)
	at net.schmizz.sshj.common.Buffer.m(Unknown Source:7)
	at ac.d.write(:6)
	at ac.d.write(Unknown Source:8)
	at dc.k.k(Unknown Source:11)
	at dc.k.f(:7)
	at dc.k.a(Unknown Source:0)
	at dc.k.i(:2)
	at wa.b.k(:9)
	at va.b.i(Unknown Source:17)
	at va.b.l(Unknown Source:0)
	at va.c.v(Unknown Source:30)
	at b7.i.b(:2)
	at e9.r0.O(Unknown Source:12)
	at ma.f0$a.a(Unknown Source:17)
	at ma.f0$a.<init>(Unknown Source:36)
	at me.zhanghai.android.files.provider.sftp.SftpPath.U(:3)
	at ma.b.X(Unknown Source:8)
	at ma.q0.<init>(Unknown Source:32)
	at va.c.b(Unknown Source:18)
	at e9.r0.Y(Unknown Source:6)
	at y9.m0.run(:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by zhanghai** [comment]
Seems like a SSHJ bug which I don't know how to fix/reproduce.

**Comment by linsui** [comment]
I can still reporoduce it. What can I do to help reproduce/fix it?

**Comment by zhanghai** [comment]
It ended up being a bug in newer version of Android's `ChooserActivity`, which will try to query the `FileProvder` with `null` selection which means all availble columns, and that included the size of the file which needs a network request to retrieve and then StrictMode would crash the `android:ui` process and leave the SFTP library in a broken state, so that the app crashes the next time the SFTP library is called.

**Comment by zhanghai** [comment]
I've submitted a workaround here and uploaded a fix for this internally.

**Comment by linsui** [comment]
Thanks!
