### ISSUE TITLE
Unable to connect to sftp server: socket failed operation not permited

### ISSUE THREAD

**Issue by dm1sh** [zhanghai/MaterialFiles#777]
When I press add, I get the following screen
![Screenshot_20220505-161924_Material Files](https://user-images.githubusercontent.com/39243579/166934434-ecb1c00b-dc18-4368-a8f8-feef89953e66.png)

Here is a logcat for app process when I reload that screen

```
<<< log_count = 20 >>>
[05-05 16:30:05.981 19567:19567 W/System.err]
java8.nio.file.FileSystemException: /: java.net.SocketException: socket failed: EPERM (Operation not permitted)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at na.c.s(:1)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at w6.k.e(:2)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at d9.b.g0(Unknown Source:5)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at s9.b0.call(:1)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at java.lang.Thread.run(Thread.java:920)

[05-05 16:30:05.981 19567:19567 W/System.err]
Caused by: me.zhanghai.android.files.provider.sftp.client.ClientException: java.net.SocketException: socket failed: EPERM (Operation not permitted)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at oa.b.a(:13)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at oa.b.i(Unknown Source:4)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at na.c.s(Unknown Source:27)

[05-05 16:30:05.981 19567:19567 W/System.err]
	... 7 more

[05-05 16:30:05.981 19567:19567 W/System.err]
Caused by: java.net.SocketException: socket failed: EPERM (Operation not permitted)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at java.net.Socket.createImpl(Socket.java:492)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at java.net.Socket.connect(Socket.java:619)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at rb.g.a(:4)

[05-05 16:30:05.981 19567:19567 W/System.err]
	at oa.b.a(:11)

[05-05 16:30:05.981 19567:19567 W/System.err]
	... 9 more
```

**Comment by zhanghai** [comment]
I don't have a good answer to this. It seems like this app is prohibited from creating network sockets. Maybe you have something in your system that turned off network access for this app?  (which isn't possible in AOSP without root.)

**Comment by dm1sh** [comment]
IDK how, but it was resolved with new update
