### ISSUE TITLE
Unable to Install .apk files stored in external storage due to It becomes corrupted

### ISSUE THREAD

**Issue by zputnyq** [zhanghai/MaterialFiles#822]
Hello,
I get a strange issue regarding installing .apk files stored in external storage (micro sd card) & it becomes no icon. The installing proccess is able to work but end up in corrupted.
Sorry I can't provide any logs, since I don't which logs to take here, I tried logcat but it shows no error on material files.
I compared using other file manager, it has no problem.

https://user-images.githubusercontent.com/31039796/177002612-a99a62fb-c917-4d75-9fee-6a41b46b761d.mp4

**Comment by zputnyq** [comment]
> Hello, I get a strange issue regarding installing .apk files stored in external storage (micro sd card) & it becomes no icon. The installing proccess is able to work but end up in corrupted. Sorry I can't provide any logs, since I don't which logs to take here, I tried logcat but it shows no error on material files. I compared using other file manager, it has no problem.
> 
> Device info : Sony Xperia M4 E2306 Stock android 6.0.1
> ScreenRecord_2022-07-02-15-12-46.mp4

Here's the log.
Hope It's correct & could help
[logcat.txt](https://github.com/zhanghai/MaterialFiles/files/9083340/logcat.txt)

**Comment by zhanghai** [comment]
The log is incomplete and the pontentially relevant part says:

```
07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m$n.p(:1)
07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.z(:1)
07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.b()
07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m$n.p(:1)
07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.z(:1)
07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.b()
07-11 17:47:49.346 W/System.err(14715): Caused by: me.zhanghai.android.files.provider.linux.syscall.SyscallException: access: Permission denied
07-11 17:47:49.346 W/System.err(14715): Caused by: me.zhanghai.android.files.provider.linux.syscall.SyscallException: access: Permission denied
07-11 17:47:49.346 W/System.err(14715): 	at me.zhanghai.android.files.provider.linux.syscall.Syscalls.access(Native Method)
07-11 17:47:49.346 W/System.err(14715): 	at me.zhanghai.android.files.provider.linux.syscall.Syscalls.access(Native Method)
07-11 17:47:49.657 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m$k.p(:1)
07-11 17:47:49.657 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.z(:1)
07-11 17:47:49.657 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.s()
07-11 17:47:49.658 W/System.err(14715): Caused by: me.zhanghai.android.files.provider.linux.syscall.SyscallException: opendir: Permission denied
07-11 17:47:49.658 W/System.err(14715): 	at me.zhanghai.android.files.provider.linux.syscall.Syscalls.opendir(Native Method)
```

But this seems to be about `opendir`, which I don't think is part of the app installation flow :thinking:

**Comment by zputnyq** [comment]
> The log is incomplete and the pontentially relevant part says:
> 
> ```
> 07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m$n.p(:1)
> 07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.z(:1)
> 07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.b()
> 07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m$n.p(:1)
> 07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.z(:1)
> 07-11 17:47:49.345 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.b()
> 07-11 17:47:49.346 W/System.err(14715): Caused by: me.zhanghai.android.files.provider.linux.syscall.SyscallException: access: Permission denied
> 07-11 17:47:49.346 W/System.err(14715): Caused by: me.zhanghai.android.files.provider.linux.syscall.SyscallException: access: Permission denied
> 07-11 17:47:49.346 W/System.err(14715): 	at me.zhanghai.android.files.provider.linux.syscall.Syscalls.access(Native Method)
> 07-11 17:47:49.346 W/System.err(14715): 	at me.zhanghai.android.files.provider.linux.syscall.Syscalls.access(Native Method)
> 07-11 17:47:49.657 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m$k.p(:1)
> 07-11 17:47:49.657 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.z(:1)
> 07-11 17:47:49.657 W/System.err(14715): 	at me.zhanghai.android.files.provider.root.m.s()
> 07-11 17:47:49.658 W/System.err(14715): Caused by: me.zhanghai.android.files.provider.linux.syscall.SyscallException: opendir: Permission denied
> 07-11 17:47:49.658 W/System.err(14715): 	at me.zhanghai.android.files.provider.linux.syscall.Syscalls.opendir(Native Method)
> ```
> 
> But this seems to be about `opendir`, which I don't think is part of the app installation flow thinking

probably something related to storage access.
I re-take a log by installing other app from material files

Unsuccess installation on external storage (micro sd card)
[logcat.txt](https://github.com/zhanghai/MaterialFiles/files/9118885/logcat.txt)

Success installation on internal storage.
[logcat.txt](https://github.com/zhanghai/MaterialFiles/files/9118933/logcat.txt)

**Comment by zhanghai** [comment]
This time the unsuccessful log didn't contain any reason for the error, just that `PackageInstaller` found the file invalid/non-existent.

**Comment by zputnyq** [comment]
> This time the unsuccessful log didn't contain any reason for the error, just that `PackageInstaller` found the file invalid/non-existent.

After trying a few times finally I found a workaround for it. It needs to wait for a few seconds when the dialog of device's package installer pop up.
