### ISSUE TITLE
[Bug] Cannot set mod after set it to 0000

### ISSUE THREAD

**Issue by HinataKato** [zhanghai/MaterialFiles#825]
https://user-images.githubusercontent.com/57648531/177662852-c1141fd7-7447-4b79-b571-14c4e50f01c7.mp4

```
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: M2012K11AC
[Display]: SQ3A.220605.009.B1
[Android Version]: 12
[API Version]: 32
[Package Name]: me.zhanghai.android.files
[Error Type]: Jvm
[Crash Time]: 2022年7月7日 08:00:45
[Stack Trace]:
java.lang.IllegalArgumentException: Collection is empty
	at java.util.EnumSet.copyOf(EnumSet.java:173)
	at am.g.R0(Unknown Source:5)
	at wc.r.d(Unknown Source:18)
	at me.zhanghai.android.files.fileproperties.permissions.SetModeDialogFragment$b.p(:6)
	at wd.i.onItemClick(:1)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1199)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3192)
	at android.widget.AbsListView$3.run(AbsListView.java:4158)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by zhanghai** [comment]
Thanks for reporting this bug!
