### ISSUE TITLE
Open archive from URI failed

### ISSUE THREAD

**Issue by asuka-mio** [zhanghai/MaterialFiles#839]
![Screenshot_20220807-125817](https://user-images.githubusercontent.com/43900799/183275978-996996a9-29ce-49a8-8c7d-3da06807f188.png)

**Comment by asuka-mio** [comment]
08-07 12:59:40.844 18316 18316 W System.err: java8.nio.file.FileSystemException: content://nekox.messenger.provider/files/storage/emulated/0/Android/data/nekox.messenger/files/documents/logcat_202208071254.txt.tar.gz: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
08-07 12:59:40.844 18316 18316 W System.err:    at fd.a.t(:10)
08-07 12:59:40.844 18316 18316 W System.err:    at d5.a.n0(:2)
08-07 12:59:40.844 18316 18316 W System.err:    at cd.d.l(:2)
08-07 12:59:40.844 18316 18316 W System.err:    at cd.e.s(:6)
08-07 12:59:40.844 18316 18316 W System.err:    at me.zhanghai.android.files.provider.root.m$k.l(:1)
08-07 12:59:40.844 18316 18316 W System.err:    at ye.s.c(:5)
08-07 12:59:40.844 18316 18316 W System.err:    at me.zhanghai.android.files.provider.root.m.z(:1)
08-07 12:59:40.844 18316 18316 W System.err:    at me.zhanghai.android.files.provider.root.m.s(Unknown Source:20)
08-07 12:59:40.844 18316 18316 W System.err:    at nd.w.g(:5)
08-07 12:59:40.844 18316 18316 W System.err:    at nd.d$a.onTransact(Unknown Source:925)
08-07 12:59:40.844 18316 18316 W System.err:    at android.os.Binder.execTransactInternal(Binder.java:1179)
08-07 12:59:40.845 18316 18316 W System.err:    at android.os.Binder.execTransact(Binder.java:1143)
08-07 12:59:40.845 18316 18316 W System.err: Caused by: me.zhanghai.android.files.provider.content.resolver.ResolverException: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
08-07 12:59:40.845 18316 18316 W System.err:    at fd.a.t(:8)
08-07 12:59:40.845 18316 18316 W System.err:    ... 11 more
08-07 12:59:40.845 18316 18316 W System.err: Caused by: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
08-07 12:59:40.845 18316 18316 W System.err:    at m3.a.G(Unknown Source:7)
08-07 12:59:40.845 18316 18316 W System.err:    at jc.h$b.c(:1)
08-07 12:59:40.845 18316 18316 W System.err:    at db.g.getValue(Unknown Source:20)
08-07 12:59:40.845 18316 18316 W System.err:    at jc.h.b(Unknown Source:4)
08-07 12:59:40.845 18316 18316 W System.err:    at fd.a.t(:6)
08-07 12:59:40.845 18316 18316 W System.err:    ... 11 more

**Comment by asuka-mio** [comment]
version 1.5.2 Google Play

**Comment by zhanghai** [comment]
```
java8.nio.file.FileSystemException: content://nekox.messenger.provider/files/storage/emulated/0/Android/data/nekox.messenger/files/documents/logcat_202208071254.txt.tar.gz: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
at me.zhanghai.android.files.provider.content.resolver.ResolverException.toFileSystemException$default(ResolverException.java:0)
at me.zhanghai.android.files.provider.content.ContentFileSystemProvider.newInputStream(ContentFileSystemProvider.java:0)
at java8.nio.file.Files.newInputStream(Files.java:0)
at me.zhanghai.android.files.provider.common.PathExtensionsKt.newInputStream(PathExtensions.kt:0)
at me.zhanghai.android.files.provider.archive.archiver.ArchiveReader.readEntries(ArchiveReader.java:0)
at me.zhanghai.android.files.provider.archive.archiver.ArchiveReader.readEntries(ArchiveReader.java:0)
at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystem.ensureEntriesLocked(LocalArchiveFileSystem.java:0)
at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystem.getDirectoryChildren(LocalArchiveFileSystem.java:0)
at me.zhanghai.android.files.provider.archive.ArchiveFileSystem.getDirectoryChildrenAsLocal(ArchiveFileSystem.java:0)
at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystemProvider.newDirectoryStream(LocalArchiveFileSystemProvider.java:0)
at me.zhanghai.android.files.provider.root.RootableFileSystemProvider$newDirectoryStream$1.invoke(RootableFileSystemProvider.java:0)
at me.zhanghai.android.files.provider.root.RootableFileSystemProvider$newDirectoryStream$1.invoke(RootableFileSystemProvider.java:0)
at me.zhanghai.android.files.provider.root.RootablePathKt.callRootable(RootablePath.kt:0)
at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.callRootable(RootableFileSystemProvider.java:0)
at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.callRootable$default(RootableFileSystemProvider.java:0)
at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.newDirectoryStream(RootableFileSystemProvider.java:20)
at me.zhanghai.android.files.provider.remote.RemoteFileSystemProviderInterface$newDirectoryStream$1.invoke(RemoteFileSystemProviderInterface.java:0)
at me.zhanghai.android.files.provider.remote.RemoteFileSystemProviderInterface$newDirectoryStream$1.invoke(RemoteFileSystemProviderInterface.java:0)
at me.zhanghai.android.files.provider.remote.IInterfaceExtensionsKt.tryRun(IInterfaceExtensions.kt:0)
at me.zhanghai.android.files.provider.remote.RemoteFileSystemProviderInterface.newDirectoryStream(RemoteFileSystemProviderInterface.java:0)
at me.zhanghai.android.files.provider.remote.IRemoteFileSystemProvider$Stub.onTransact(IRemoteFileSystemProvider.java:925)
at android.os.Binder.execTransactInternal(Binder.java:1179)
at android.os.Binder.execTransact(Binder.java:1143)
Caused by: me.zhanghai.android.files.provider.content.resolver.ResolverException: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
at me.zhanghai.android.files.provider.content.resolver.Resolver.openAssetFileDescriptor(Resolver.java:0)
at me.zhanghai.android.files.provider.content.resolver.Resolver.openInputStream(Resolver.java:0)
at me.zhanghai.android.files.provider.content.ContentFileSystemProvider.newInputStream(ContentFileSystemProvider.java:0)
... 11 more
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
at me.zhanghai.android.files.app.AppProviderKt.getApplication(AppProvider.kt:7)
at me.zhanghai.android.files.app.SystemServicesKt$contentResolver$2.invoke(SystemServices.kt:0)
at me.zhanghai.android.files.app.SystemServicesKt$contentResolver$2.invoke(SystemServices.kt:0)
at kotlin.SynchronizedLazyImpl.getValue(SynchronizedLazyImpl.java:20)
at me.zhanghai.android.files.app.SystemServicesKt.getContentResolver(SystemServices.kt:4)
at me.zhanghai.android.files.provider.content.resolver.Resolver.openAssetFileDescriptor(Resolver.java:0)
at me.zhanghai.android.files.provider.content.resolver.Resolver.openInputStream(Resolver.java:0)
at me.zhanghai.android.files.provider.content.ContentFileSystemProvider.newInputStream(ContentFileSystemProvider.java:0)
... 11 more
```

**Comment by zhanghai** [comment]
How can I reproduce this? And what happens if you pull to refresh?

**Comment by asuka-mio** [comment]
Sorry to tell that after I totally dropped sdcardfs and turn to fuse, and upgrade to Android 13 from Android 12, I can't reproduce that anymore. System environment changed a bit rapidly, and sorry that I can't revert it back to reproduce that bug.
