### ISSUE TITLE
Missing dependency about LZMA

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#91]
Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
Caused by java.lang.NoClassDefFoundError
Failed resolution of: Lorg/tukaani/xz/LZMA2Options;
Caused by java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tukaani/xz/LZMA2Options;
       at org.apache.commons.compress.archivers.sevenz.LZMADecoder.(Unknown Source:3)
       at org.apache.commons.compress.archivers.sevenz.Coders$1.(Unknown Source:17)
       at org.apache.commons.compress.archivers.sevenz.Coders.(Unknown Source:2)
       at org.apache.commons.compress.archivers.sevenz.Coders.addDecoder(Coders.java)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.access$000(SevenZFile.java:75)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.access$100(SevenZFile.java:122)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.(Unknown Source:22)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.(Unknown Source:26)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.(Unknown Source:1)
       at me.zhanghai.android.files.provider.archive.reader.ArchiveReader.readEntries(ArchiveReader.java:203)
       at me.zhanghai.android.files.provider.archive.reader.ArchiveReader.getZipFileNameEncoding(ArchiveReader.java:5)
       at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystem.ensureEntriesLocked(LocalArchiveFileSystem.java:12)
       at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystem.getDirectoryChildren(LocalArchiveFileSystem.java:3)
       at me.zhanghai.android.files.provider.archive.ArchiveFileSystem.getDirectoryChildrenAsLocal(ArchiveFileSystem.java:4)
       at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystemProvider.checkAccess(LocalArchiveFileSystemProvider.java:12)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java)
       at me.zhanghai.android.files.provider.root.-$$Lambda$RootableFileSystemProvider$KWGbC0g1KMQlbbd9vh3V161YPFI.apply(-.java:6)
       at me.zhanghai.android.files.provider.root.RootUtils.acceptRootable(RootUtils.java:21)
       at me.zhanghai.android.files.provider.root.RootUtils.acceptRootable(RootUtils.java:21)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:4)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:4)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:5)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:5)
       at java8.nio.file.Files.newDirectoryStream(Files.java:6)
       at me.zhanghai.android.files.filelist.FileListLiveData$1.doInBackground(FileListLiveData.java:6)
       at me.zhanghai.android.files.filelist.FileListLiveData$1.doInBackground(FileListLiveData.java:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
Caused by java.lang.ClassNotFoundException
Didn't find class "org.tukaani.xz.LZMA2Options" on path: DexPathList[[zip file "/data/app/me.zhanghai.android.files-OxIhThR_6gVK2FR39HwNaQ==/base.apk"],nativeLibraryDirectories=[/data/app/me.zhanghai.android.files-OxIhThR_6gVK2FR39HwNaQ==/lib/arm64, /data/app/me.zhanghai.android.files-OxIhThR_6gVK2FR39HwNaQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
Caused by java.lang.ClassNotFoundException: Didn't find class "org.tukaani.xz.LZMA2Options" on path: DexPathList[[zip file "/data/app/me.zhanghai.android.files-OxIhThR_6gVK2FR39HwNaQ==/base.apk"],nativeLibraryDirectories=[/data/app/me.zhanghai.android.files-OxIhThR_6gVK2FR39HwNaQ==/lib/arm64, /data/app/me.zhanghai.android.files-OxIhThR_6gVK2FR39HwNaQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at org.apache.commons.compress.archivers.sevenz.LZMADecoder.(Unknown Source:3)
       at org.apache.commons.compress.archivers.sevenz.Coders$1.(Unknown Source:17)
       at org.apache.commons.compress.archivers.sevenz.Coders.(Unknown Source:2)
       at org.apache.commons.compress.archivers.sevenz.Coders.addDecoder(Coders.java)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.access$000(SevenZFile.java:75)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.access$100(SevenZFile.java:122)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.(Unknown Source:22)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.(Unknown Source:26)
       at org.apache.commons.compress.archivers.sevenz.SevenZFile.(Unknown Source:1)
       at me.zhanghai.android.files.provider.archive.reader.ArchiveReader.readEntries(ArchiveReader.java:203)
       at me.zhanghai.android.files.provider.archive.reader.ArchiveReader.getZipFileNameEncoding(ArchiveReader.java:5)
       at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystem.ensureEntriesLocked(LocalArchiveFileSystem.java:12)
       at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystem.getDirectoryChildren(LocalArchiveFileSystem.java:3)
       at me.zhanghai.android.files.provider.archive.ArchiveFileSystem.getDirectoryChildrenAsLocal(ArchiveFileSystem.java:4)
       at me.zhanghai.android.files.provider.archive.LocalArchiveFileSystemProvider.checkAccess(LocalArchiveFileSystemProvider.java:12)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java)
       at me.zhanghai.android.files.provider.root.-$$Lambda$RootableFileSystemProvider$KWGbC0g1KMQlbbd9vh3V161YPFI.apply(-.java:6)
       at me.zhanghai.android.files.provider.root.RootUtils.acceptRootable(RootUtils.java:21)
       at me.zhanghai.android.files.provider.root.RootUtils.acceptRootable(RootUtils.java:21)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:4)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:4)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:5)
       at me.zhanghai.android.files.provider.root.RootableFileSystemProvider.acceptRootable(RootableFileSystemProvider.java:5)
       at java8.nio.file.Files.newDirectoryStream(Files.java:6)
       at me.zhanghai.android.files.filelist.FileListLiveData$1.doInBackground(FileListLiveData.java:6)
       at me.zhanghai.android.files.filelist.FileListLiveData$1.doInBackground(FileListLiveData.java:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by zhanghai** [comment]
Added dependency `org.tukaani:xz:1.8`.
