### ISSUE TITLE
UnsupportedOperationException using ACTION_OPEN_DOCUMENT with DocumentsContract.EXTRA_INITIAL_URI

### ISSUE THREAD

**Issue by k3b** [zhanghai/MaterialFiles#948]
I have "Material Files" Version 1.5.2 (31) installed from F-Droid-Repository.

On my Android-10 handset (not rooted, Manufacturer = LG)

My app wants to open a csv file with a pre-choosen file (the file that was last used in the app)

Instead of the file list the FilePicker "Material Files" shows the error message "java.lang.UnsupportedOperationException"

Here is the code that open the FilePicker

```
    private void openFilePicker() {
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT)
                .addCategory(Intent.CATEGORY_OPENABLE)
                .setType("text/csv")
                .putExtra(Intent.EXTRA_TITLE, getString(R.string.title_open_file))
                ;

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            String lastUsed = PreferenceManager
                    .getDefaultSharedPreferences(this.getApplicationContext())
                            .getString(KEY_CSV_FILE_URI, null);
            if (lastUsed != null) {
                // Optionally, specify a URI for the file that should appear in the
                // system file picker when it loads.

                // on error this is the content of DocumentsContract.EXTRA_INITIAL_URI
                // android.provider.extra.INITIAL_URI=
                // content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDownload%252Fcsv%252Fchanges.csv
                // url-decoded content://me.zhanghai.android.files.file_provider/file:///storage/emulated/0/Download/csv/changes.csv
                intent.putExtra(DocumentsContract.EXTRA_INITIAL_URI, Uri.parse(lastUsed));
            }
        }

        Log.d(TAG,intent.toString() + " Extras " + intent.getExtras());
        startActivityForResult(intent, VIEW_CSV_FILE);
    }

```

i get this error in logcat

```
java.lang.UnsupportedOperationException
	at ea.a.s(Unknown Source:33)
	at u6.k.e(:2)
	at d.b.v0(Unknown Source:5)
	at q9.c0.call(:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

without the extra parameter DocumentsContract.EXTRA_INITIAL_URI "Material Files" works as expected.

-----

Here is the full stacktrace

```
2023-04-05 20:06:28.812 21469-21469 CSVTableActivity        de.k3b.android.csvdroid              D  Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/csv (has extras) } 
						Extras Bundle[{android.provider.extra.INITIAL_URI=content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDownload%252Fcsv%252Fchanges.csv, android.intent.extra.TITLE=Open ...}]

2023-04-05 20:06:29.518  3515-4706  ActivityTaskManager     system_server                        I  START u0 {act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/csv cmp=me.zhanghai.android.files/.filelist.FileListActivity (has extras)} from uid 10731
2023-04-05 20:06:29.519  3515-4706  ActivityTaskManager     system_server                        D  TaskLaunchParamsModifier:task=null activity=ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t-1} display-from-source=0 display-id=0 display-windowing-mode=1
2023-04-05 20:06:29.519  3515-4706  ActivityTaskManager     system_server                        D  TaskLaunchParamsModifier:task=null activity=ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t-1} display-from-source=0 display-id=0 display-windowing-mode=1 inherit-from-source=fullscreen activity-options-fullscreen=Rect(0, 0 - 0, 0) non-freeform-display maximized-bounds
2023-04-05 20:06:29.522   692-783   SurfaceFlinger          surfaceflinger                       I  Create ContainerLayer(0xaeb5d000) AppWindowToken{ee54b36 token=Token{6fee4d1 ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}}}#0 (0 x 0)
2023-04-05 20:06:29.531  4502-5476  AutoGameModeMonitor     com.lge.systemserver                 D  Display : 0  Package : u0 me.zhanghai.android.files  PrevPackage : u0 de.k3b.android.csvdroid
2023-04-05 20:06:29.590  3515-6310  ActivityTaskManager     system_server                        I  The Process me.zhanghai.android.files Already Exists in BG. So sending its PID: 19796
2023-04-05 20:06:29.590  3515-6310  ActivityTaskManager     system_server                        I  setVisibility true ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}
2023-04-05 20:06:29.593  3515-6310  ActivityTaskManager     system_server                        I  setVisibility true ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}
2023-04-05 20:06:29.595  3515-6310  ActivityTaskManager     system_server                        I  setVisibility true ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}
2023-04-05 20:06:29.595  4122-4122  GameSoundHandler        com.android.systemui                 I  onTopPackageChanged mTopPackageName = me.zhanghai.android.files topPackageName = me.zhanghai.android.files
2023-04-05 20:06:29.596  4122-4122  NoAlertsDu...ameHandler com.android.systemui                 I  onTopPackageChanged mTopPackageName = me.zhanghai.android.files topPackageName = me.zhanghai.android.files
2023-04-05 20:06:29.715   692-2242  SurfaceFlinger          surfaceflinger                       I  Create ContainerLayer(0xaea97000) 1c9e10 me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity#0 (0 x 0)
2023-04-05 20:06:29.729   692-2242  SurfaceFlinger          surfaceflinger                       I  Create BufferLayer(0xaeb5a800) me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity@19796#0 (720 x 1440)
2023-04-05 20:06:29.732  3515-3653  StatusBarManagerService system_server                        I  disableLocked(#0, /u0, 0x0, 1), by Window{1c9e10 u0 me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity}
2023-04-05 20:06:29.732  3515-6310  WindowManager           system_server                        V  Changing focus from Window{1c9e10 u0 me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity} to Window{1c9e10 u0 me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity} displayId=0 and set InputFoucs to newFocus window. updateInputWindows ? true

2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  java.lang.UnsupportedOperationException
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at ea.a.s(Unknown Source:33)
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at u6.k.e(:2)
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at d.b.v0(Unknown Source:5)
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at q9.c0.call(:1)
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-04-05 20:06:29.821 19796-19796 System.err              me.zhanghai.android.files            W  	at java.lang.Thread.run(Thread.java:919)

2023-04-05 20:06:29.825   692-2242  SurfaceFlinger          surfaceflinger                       I  Create ContainerLayer(0xaeb44000) Surface(name=AppWindowToken{ee54b36 token=Token{6fee4d1 ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}}})/@0xd6c4a1a - animation-leash#0 (0 x 0)
2023-04-05 20:06:29.826   692-2241  SurfaceFlinger          surfaceflinger                       I  Create ContainerLayer(0xae7c4000) Surface(name=AppWindowToken{ee54b36 token=Token{6fee4d1 ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}}})/@0xd6c4a1a - animation-bounds#0 (0 x 0)
2023-04-05 20:06:29.838  3515-3653  StatusBarManagerService system_server                        I  disableLocked(#0, /u0, 0x0, 1), by Window{1c9e10 u0 me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity}
2023-04-05 20:06:29.847  3515-3675  ActivityTaskManager     system_server                        I  Displayed me.zhanghai.android.files/.filelist.FileListActivity: +310ms
2023-04-05 20:06:29.859  3515-4706  InputDispatcher         system_server                        D  Focus entered window: Window{1c9e10 u0 me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity} in display 0
2023-04-05 20:06:29.859   692-692   MiniDump                surfaceflinger                       I  -------------------------------------------------------------------------------------------
                                                                                                     Handle    |  Comp Type |  Transform |  Alpha |  Disp Frame (LTRB) |  Source Crop (LTRB) | Disp[0, p] "Internal display"
                                                                                                    0xb305e800 |     DEVICE |          0 | 0.994 |    0    0  720 1440 |   0.0   0.0 720.0 1440.0 | de.k3b.android.csvdroid/d[...].CSVTableActivity@21469#0
                                                                                                    0xaeb5a800 |     DEVICE |          0 | 0.232 |    0  285  720 1440 |   0.0   0.0 720.0 1155.0 | me.zhanghai.android.files[...].FileListActivity@19796#0
                                                                                                    0xb10ed000 |     DEVICE |          0 | 1.000 |    0    0  720   42 |   0.0   0.0 720.0  42.0 | StatusBar@4122#0
                                                                                                    0xb10e8000 |     DEVICE |          0 | 1.000 |    0 1356  720 1440 |   0.0   0.0 720.0  84.0 | NavigationBar0@4122#0
2023-04-05 20:06:30.109   692-692   SurfaceFlinger          surfaceflinger                       I  Remove ContainerLayer(0xae7c4000) Surface(name=AppWindowToken{ee54b36 token=Token{6fee4d1 ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}}})/@0xd6c4a1a - animation-bounds#0 (-1 x -1)
2023-04-05 20:06:30.109   692-692   SurfaceFlinger          surfaceflinger                       I  Remove ContainerLayer(0xaeb44000) Surface(name=AppWindowToken{ee54b36 token=Token{6fee4d1 ActivityRecord{41cc7f8 u0 me.zhanghai.android.files/.filelist.FileListActivity t16361}}})/@0xd6c4a1a - animation-leash#0 (-1 x -1)
2023-04-05 20:06:30.116   692-692   MiniDump                surfaceflinger                       I  -------------------------------------------------------------------------------------------
                                                                                                     Handle    |  Comp Type |  Transform |  Alpha |  Disp Frame (LTRB) |  Source Crop (LTRB) | Disp[0, p] "Internal display"
                                                                                                    0xaeb5a800 |     DEVICE |          0 | 1.000 |    0    0  720 1440 |   0.0   0.0 720.0 1440.0 | me.zhanghai.android.files[...].FileListActivity@19796#0
                                                                                                    0xb10ed000 |     DEVICE |          0 | 1.000 |    0    0  720   42 |   0.0   0.0 720.0  42.0 | StatusBar@4122#0
                                                                                                    0xb10e8000 |     DEVICE |          0 | 1.000 |    0 1356  720 1440 |   0.0   0.0 720.0  84.0 | NavigationBar0@4122#0

```

**Comment by zhanghai** [comment]
The initial URI can't be a content URI (even if it's backed by the FileProvider of Material Files). It can be other things though, see `IntentPathExtensions.kt`
