### ISSUE TITLE
App crashes while trying to generate thumbnail

### ISSUE THREAD

**Issue by khaled-0** [zhanghai/MaterialFiles#968]
This mostly happens with folders containing a lot of large videos. 
Expected behavior: Silently fail and don't show thumbnail for those files.
Current Behavior: App crashes with the following error.

```
msg: java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
stacktrace: java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
	at android.media.MediaMetadataRetriever.native_finalize(Native Method)
	at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:1109)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
	at java.lang.Daemons$Daemon.run(Daemons.java:140)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Massedil** [comment]
I also experience this problem : 

```
10-27 09:09:35.675 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32278), adj 965,
10-27 09:09:35.882 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32301), adj 955,
10-27 09:09:36.118 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32256), adj 945,
10-27 09:09:36.146 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32537), adj 935,
10-27 09:09:36.823 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (913), adj 925,
10-27 09:09:36.876 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (1068), adj 915,
10-27 09:09:36.902 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (1136), adj 905,
10-27 09:09:37.134 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32480), adj 700,
10-27 09:09:40.823 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32385), adj 200,
10-27 09:09:41.315 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32119), adj 200,
10-27 09:09:41.353 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32672), adj 200,
10-27 09:09:41.434 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32703), adj 200,
10-27 09:09:41.721 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32679), adj 200,
10-27 09:09:41.873 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32649), adj 200,
10-27 09:09:42.255 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32727), adj 905,
10-27 09:09:42.823 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (32113), adj 100,
10-27 09:09:43.506 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (2076), adj 200,
10-27 09:09:43.837 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (662), adj 100,
10-27 09:09:44.026 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (983), adj 100,
10-27 09:09:44.079 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (1483), adj 100,
10-27 09:09:44.116 I/lowmemorykiller(0): Killing 'xxxxxxxxxx' (1319), adj 100,
```

Folder with more than 100 videos. 

Phone freeze until MaterialFiles crashes itself and all my apps are unloaded from memory.

Samsung Galaxy S5 on LineageOS 18.1.

I'm available to test a fix if it can help.

**Comment by sniirful** [comment]
I have tried it for very little and certainly haven't gone into debug mode, but it seems like it crashes when it takes too long to load a preview. I have noticed it especially with a CalDAV server and big videos.

**Comment by zhanghai** [comment]
Yes I do need a crash stacktrace to be able to do anything. I haven't seen this on my phone.
